version: '3.8'

# 🚀 Tiation SaaS - Minimal Test Environment
# Only core databases and tools for testing

networks:
  tiation-network:
    driver: bridge

volumes:
  postgres_data:
  mongodb_data:
  redis_data:

services:
  # ===============================================
  # 🗄️  CORE DATABASES
  # ===============================================
  
  postgres:
    image: postgres:15-alpine
    container_name: tiation-postgres-minimal
    restart: unless-stopped
    environment:
      POSTGRES_DB: tiation_dev
      POSTGRES_USER: tiation
      POSTGRES_PASSWORD: dev123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tiation-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tiation"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo:6.0
    container_name: tiation-mongodb-minimal
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: tiation
      MONGO_INITDB_ROOT_PASSWORD: dev123
      MONGO_INITDB_DATABASE: tiation_gaming
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - tiation-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: tiation-redis-minimal
    restart: unless-stopped
    command: redis-server --requirepass dev123 --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - tiation-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "dev123", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # ===============================================
  # 🔧 DEVELOPMENT TOOLS
  # ===============================================
  
  adminer:
    image: adminer:latest
    container_name: tiation-adminer-minimal
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - tiation-network
    depends_on:
      - postgres

  mongo-express:
    image: mongo-express:latest
    container_name: tiation-mongo-express-minimal
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: tiation
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev123
      ME_CONFIG_MONGODB_URL: mongodb://tiation:dev123@mongodb:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8083:8081"
    networks:
      - tiation-network
    depends_on:
      - mongodb

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: tiation-redis-commander-minimal
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379:0:dev123
    ports:
      - "8082:8081"
    networks:
      - tiation-network
    depends_on:
      - redis
