console.log('🚀 Tiation Automation Workspace');
console.log('✨ Enterprise-grade AI-powered automation platform');
console.log('📦 Version: 1.0.0');
console.log('');
console.log('Available commands:');
console.log('  npm run dev     - Start development server');
console.log('  npm run build   - Build for production');
console.log('  npm run smol-dev - Run smol-dev-js AI assistant');
console.log('');
console.log('⚡ Ready to automate!');
