mesh:
  discovery_interval: 1.0
  max_nodes: 100
  min_connections: 2
  max_connections: 5
  transmission_power: 1.0
  healing_interval: 2.0

neural:
  learning_rate: 0.01
  pattern_threshold: 0.8
  history_size: 100
  adaptation_rate: 0.001

features:
  self_repair: true
  load_balancing: true
  path_optimization: true
  knowledge_sharing: true

logging:
  level: INFO
  file: logs/mesh.log
  max_size: 10MB
  backup_count: 3

security:
  encryption_enabled: true
  key_rotation_interval: 3600
  auth_required: true
